version: '3.8'

services:
  app:
    image: webrtc:latest
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT : ${PORT}
      APP_CREDENSIAL : ${APP_CREDENSIAL}
      NODE_ENV : production
      DATABASE_URL : "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public"
    command: sh -c "npx prisma migrate deploy && node dist/index.js"
  
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: